# Generated by Django 5.2.4 on 2025-08-01 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_customer_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-created_at'], 'permissions': [('management_role_access', 'Can access management-level features'), ('client_manege_access', 'Can access client-manege features')], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
