# Generated by Django 5.2.4 on 2025-08-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationitem',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
